#!/bin/bash
set -euo pipefail

# claude-setup installer
# Creates symlinks from ~/.claude/ and ~/.mempalace/ → this repo
# Generates ~/.claude-setup/config.sh with per-machine paths

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UPDATE_MODE=0

for arg in "$@"; do
  case "$arg" in
    --update) UPDATE_MODE=1 ;;
    --help|-h)
      cat << 'EOF'
Usage: ./install.sh [--update]

Options:
  --update  Skip prompts, re-validate symlinks only (uses existing config).
  --help    Show this help.
EOF
      exit 0
      ;;
  esac
done

echo "=== claude-setup installer ==="
echo "Repo: $REPO_DIR"
echo ""

# ---- Prerequisite checks ----

check_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: '$1' not found. Please install it and re-run."
    return 1
  fi
}

echo "Checking prerequisites..."
check_cmd git
check_cmd rsync
check_cmd python3

if ! command -v claude >/dev/null 2>&1; then
  echo "WARNING: 'claude' CLI not found. Install from https://claude.ai/code"
fi

if ! python3 -c "import mempalace" 2>/dev/null; then
  echo "WARNING: mempalace Python package not installed. Run: pip3 install mempalace"
fi

echo "Prerequisites OK"
echo ""

# ---- Detect or prompt for paths ----

detect_path() {
  shift  # discard the name arg used for readability
  for candidate in "$@"; do
    if [ -d "$candidate" ]; then
      echo "$candidate"
      return 0
    fi
  done
  return 1
}

prompt_path() {
  local name="$1"
  local default="$2"
  local value
  read -rp "$name [$default]: " value
  echo "${value:-$default}"
}

CONFIG_FILE="$HOME/.claude-setup/config.sh"
mkdir -p "$HOME/.claude-setup"

if [ "$UPDATE_MODE" -eq 1 ] && [ -f "$CONFIG_FILE" ]; then
  echo "Update mode — sourcing existing config"
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
else
  echo "Detecting per-machine paths..."

  WORKSPACE_A_REPO=$(detect_path "WORKSPACE_A_REPO" "$HOME/REPOS/workspace-a" "$HOME/code/workspace-a" "$HOME/projects/workspace-a" || true)
  if [ -z "${WORKSPACE_A_REPO:-}" ]; then
    WORKSPACE_A_REPO=$(prompt_path "WORKSPACE_A_REPO path" "$HOME/REPOS/workspace-a")
  else
    echo "  WORKSPACE_A_REPO: $WORKSPACE_A_REPO"
  fi

  WORKSPACE_B_REPO=$(detect_path "WORKSPACE_B_REPO" "$HOME/REPOS/workspace-b" "$HOME/code/workspace-b" "$HOME/projects/workspace-b" || true)
  if [ -z "${WORKSPACE_B_REPO:-}" ]; then
    WORKSPACE_B_REPO=$(prompt_path "WORKSPACE_B_REPO path (optional, leave blank to skip)" "")
  else
    echo "  WORKSPACE_B_REPO: $WORKSPACE_B_REPO"
  fi

  BACKUP_SHARE=$(prompt_path "BACKUP_SHARE (for palace backups)" "/Volumes/NAS")
  SNAPSHOT_RETENTION_DAYS=30

  cat > "$CONFIG_FILE" << EOF
#!/bin/bash
# Generated by claude-setup install.sh
export WORKSPACE_A_REPO="$WORKSPACE_A_REPO"
export WORKSPACE_B_REPO="$WORKSPACE_B_REPO"
export BACKUP_SHARE="$BACKUP_SHARE"
export SNAPSHOT_RETENTION_DAYS=$SNAPSHOT_RETENTION_DAYS
EOF
  echo "Wrote $CONFIG_FILE"
fi

echo ""

# ---- Backup existing config before symlinking ----

BACKUP_DIR="$HOME/.claude/backup-pre-install/$(date +%Y%m%d-%H%M%S)"

backup_if_exists() {
  local path="$1"
  if [ -e "$path" ] && [ ! -L "$path" ]; then
    mkdir -p "$(dirname "$BACKUP_DIR/$path")"
    mv "$path" "$BACKUP_DIR/$path"
    echo "  Backed up: $path → $BACKUP_DIR"
  elif [ -L "$path" ]; then
    rm "$path"
  fi
}

echo "Backing up existing files to $BACKUP_DIR if needed..."

mkdir -p "$HOME/.claude/hooks" "$HOME/.claude/context" "$HOME/.claude/skills" "$HOME/.mempalace/hooks"

# ---- Create symlinks ----

make_symlink() {
  local src="$1"
  local dst="$2"
  backup_if_exists "$dst"
  mkdir -p "$(dirname "$dst")"
  ln -s "$src" "$dst"
  echo "  $dst → $src"
}

echo ""
echo "Creating symlinks..."

# Claude global config
make_symlink "$REPO_DIR/claude/CLAUDE.md" "$HOME/.claude/CLAUDE.md"
make_symlink "$REPO_DIR/claude/settings.json" "$HOME/.claude/settings.json"

# Claude hooks
make_symlink "$REPO_DIR/claude/hooks/session-context.sh" "$HOME/.claude/hooks/session-context.sh"
make_symlink "$REPO_DIR/claude/hooks/pre-commit-checks.sh" "$HOME/.claude/hooks/pre-commit-checks.sh"
make_symlink "$REPO_DIR/claude/hooks/pre-push-checks.sh" "$HOME/.claude/hooks/pre-push-checks.sh"

# ---- Claude context: symlink if present, otherwise copy templates and abort ----

CONTEXT_DIR="$REPO_DIR/claude/context"
CONTEXT_TEMPLATE_DIR="$REPO_DIR/claude/context-templates"

if [ -d "$CONTEXT_DIR" ] && [ "$(ls -A "$CONTEXT_DIR" 2>/dev/null)" ]; then
  # Private context exists in the repo (full private clone)
  backup_if_exists "$HOME/.claude/context"
  make_symlink "$CONTEXT_DIR" "$HOME/.claude/context"
  echo "  $HOME/.claude/context → $CONTEXT_DIR (symlinked)"
else
  # Public clone — no private context. Copy templates.
  echo ""
  echo "WARNING: claude/context/ not found in this repo."
  echo "This is expected for the public version of claude-setup."
  echo ""
  echo "Copying context templates from $CONTEXT_TEMPLATE_DIR..."

  backup_if_exists "$HOME/.claude/context"
  mkdir -p "$HOME/.claude/context"
  cp -R "$CONTEXT_TEMPLATE_DIR"/* "$HOME/.claude/context/"
  echo "  Copied templates to $HOME/.claude/context/"
  echo ""
  echo "=== ACTION REQUIRED ==="
  echo "Edit the copied template files in ~/.claude/context/ with your own"
  echo "domain-specific content. Rename workspace-a/workspace-b to your"
  echo "actual workspace names. Then re-run:"
  echo ""
  echo "  ./install.sh --update"
  echo ""
  echo "Install aborted until context templates are populated."
  exit 1
fi

# Claude skills (symlink individual skill dirs — easier to add new ones)
for skill_dir in "$REPO_DIR/claude/skills"/*; do
  [ -d "$skill_dir" ] || continue
  name=$(basename "$skill_dir")
  make_symlink "$skill_dir" "$HOME/.claude/skills/$name"
done

# Mempalace config files
make_symlink "$REPO_DIR/mempalace/config.json" "$HOME/.mempalace/config.json"
make_symlink "$REPO_DIR/mempalace/wing_config.json" "$HOME/.mempalace/wing_config.json"
make_symlink "$REPO_DIR/mempalace/identity.txt" "$HOME/.mempalace/identity.txt"

# Mempalace hooks
make_symlink "$REPO_DIR/mempalace/hooks/mempal_save_hook.sh" "$HOME/.mempalace/hooks/mempal_save_hook.sh"
make_symlink "$REPO_DIR/mempalace/hooks/mempal_precompact_hook.sh" "$HOME/.mempalace/hooks/mempal_precompact_hook.sh"

# Mempalace mining scripts (symlink into ~/.mempalace/ root for backward compat with existing launchers)
make_symlink "$REPO_DIR/mempalace/mine/mine-all.sh" "$HOME/.mempalace/mine-all.sh"
make_symlink "$REPO_DIR/mempalace/mine/mine-frontend.sh" "$HOME/.mempalace/mine-frontend.sh"
make_symlink "$REPO_DIR/mempalace/mine/mine-guider.sh" "$HOME/.mempalace/mine-guider.sh"

# ---- Fix palace_path in config.json for this machine ----

echo ""
echo "Patching mempalace palace_path for this user..."

MEMPALACE_CONFIG="$REPO_DIR/mempalace/config.json"
EXPECTED_PATH="$HOME/.mempalace/palace"
CURRENT_PATH=$(python3 -c "import json; print(json.load(open('$MEMPALACE_CONFIG'))['palace_path'])")

if [ "$CURRENT_PATH" != "$EXPECTED_PATH" ]; then
  python3 << PYEOF
import json
with open('$MEMPALACE_CONFIG', 'r') as f:
    cfg = json.load(f)
cfg['palace_path'] = '$EXPECTED_PATH'
with open('$MEMPALACE_CONFIG', 'w') as f:
    json.dump(cfg, f, indent=2)
PYEOF
  echo "  Updated palace_path: $CURRENT_PATH → $EXPECTED_PATH"
else
  echo "  palace_path already correct: $EXPECTED_PATH"
fi

# ---- Make all .sh files executable ----

echo ""
echo "Making scripts executable..."
find "$REPO_DIR" -name "*.sh" -exec chmod +x {} \;

# ---- Optional: SessionEnd hook for auto-backup ----

if [ "$UPDATE_MODE" -eq 0 ]; then
  echo ""
  read -rp "Enable SessionEnd auto-backup hook? (y/N): " enable_session_hook
  if [[ "$enable_session_hook" =~ ^[Yy]$ ]]; then
    echo ""
    echo "To enable, manually add this to ~/.claude/settings.json under 'hooks':"
    echo ""
    cat "$REPO_DIR/templates/session-end-hook.json"
    echo ""
    echo "(claude-setup does not auto-modify settings.json to avoid corrupting user customizations.)"
  fi

  # ---- Optional: launchd schedule ----

  read -rp "Enable weekly scheduled backup via launchd? (y/N): " enable_launchd
  if [[ "$enable_launchd" =~ ^[Yy]$ ]]; then
    PLIST_SRC="$REPO_DIR/templates/com.claude-setup.mempalace-backup.plist"
    PLIST_DST="$HOME/Library/LaunchAgents/com.claude-setup.mempalace-backup.plist"

    sed -e "s|{{REPO_DIR}}|$REPO_DIR|g" -e "s|{{HOME}}|$HOME|g" "$PLIST_SRC" > "$PLIST_DST"
    launchctl load "$PLIST_DST" 2>/dev/null || true
    echo "  Installed: $PLIST_DST"
    echo "  Runs weekly at 03:00 local time"
  fi

  # ---- Offer palace restore ----

  if [ -d "$BACKUP_SHARE/claude-backup/mempalace" ]; then
    echo ""
    read -rp "Existing palace backup found at $BACKUP_SHARE/claude-backup/mempalace. Restore now? (y/N): " do_restore
    if [[ "$do_restore" =~ ^[Yy]$ ]]; then
      "$REPO_DIR/mempalace/backup/restore-palace.sh"
    fi
  fi
fi

echo ""
echo "=== Install complete ==="
echo "Config: $CONFIG_FILE"
echo "Backups of prior files: $BACKUP_DIR (if any)"
echo ""
echo "Next steps:"
echo "  - Start a new Claude Code session to test session-context.sh"
echo "  - Run 'python3 -m mempalace status' to verify mempalace config"
echo "  - Run '$REPO_DIR/mempalace/backup/backup-palace.sh' to test backup"
