#!/bin/bash
# Per-machine paths for claude-setup. Generated by install.sh.
# Edit this file and re-run install to update.

# Path to the Thrive workspace repo (used for service-graph resolution)
export THRIVE_REPO="$HOME/REPOS/Thrive"

# Path to the Guider platform repo (Rush monorepo root)
export GUIDER_REPO="$HOME/REPOS/guider/platform"

# Backup destination (NAS, external drive, synced folder)
export BACKUP_SHARE="/Volumes/NAS"

# Days to retain tarball snapshots in $BACKUP_SHARE/claude-backup/snapshots/
export SNAPSHOT_RETENTION_DAYS=30
