#!/bin/bash
# Per-machine paths for claude-setup. Generated by install.sh.
# Edit this file and re-run install to update.

# Path to your primary workspace repo (used for service-graph resolution and mining).
export WORKSPACE_A_REPO="$HOME/REPOS/workspace-a"

# Path to a second workspace repo, if you have one. Leave unset if not used.
export WORKSPACE_B_REPO="$HOME/REPOS/workspace-b"

# Backup destination (NAS, external drive, synced folder)
export BACKUP_SHARE="/Volumes/NAS"

# Days to retain tarball snapshots in $BACKUP_SHARE/claude-backup/snapshots/
export SNAPSHOT_RETENTION_DAYS=30
